server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost/customer
    username: ire
    password: bamidele
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  main:
    web-application-type: servlet
